ratings:
  namespace: student33-bookinfo-prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  image: ghcr.io/tatarsrw/bookinfo-ratings
  tag: prd
ingress:
  host: sitkmutt.bookinfo.prd.opsta.net
  path: "/student33/ratings(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-prd-ratings-mongodb:27017/ratings
  MONGO_DB_USERNAME: ratings
extraEnvSecret:
  MONGO_DB_PASSWORD:
    bookinfo-prd-ratings-mongodb-secret: mongodb-password