name: dev-env
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          ...
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          ...


      - name: Checkout code
        uses: actions/checkout@v2
      - run: docker build -t ghcr.io/tatarsrw/bookinfo-ratings:dev .
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker push ghcr.io/tatarsrw/bookinfo-ratings:dev